- hosts: 
    - master-node
    - worker-node
  become: yes
  remote_user: benjamin
  roles:
    - prepare_nodes
- hosts: master-node
  become: yes
  remote_user: benjamin
  gather_facts: true
  roles:
    - install_master
- hosts:
    - master-node
    - worker-node
  become: yes
  remote_user: benjamin
  gather_facts: true
  roles:
    - install_node